### ISSUE TITLE
Breaking updates of transitive dependencies are(often) breaking changes for the tool itself

### ISSUE THREAD

**Issue by andreaTP** [codacy/codacy-remark-lint#142]
* **I'm submitting a ...**
[X] bug report

* **Summary**
Despite the fact that we simply bumped the patch version we have all kind of different behavior from the tool.
To reproduce:
```bash
git clone git@github.com:jilleJr/Newtonsoft.Json-for-Unity.Converters.git
docker run --rm -it -v $PWD/Newtonsoft.Json-for-Unity.Converters:/src codacy/codacy-remark-lint:1.0.169 # 3 issues found
docker run --rm -it -v $PWD/Newtonsoft.Json-for-Unity.Converters:/src codacy/codacy-remark-lint:1.0.167 # in production cloud - 2 issues found
docker run --rm -it -v $PWD/Newtonsoft.Json-for-Unity.Converters:/src codacy/codacy-remark-lint:1.0.159 # possibly in the CLI - 32 issues found
```
I think we are currently experiencing a major regression, i.e.:
__32 to 2 issues detected__

**Comment by lolgab** [comment]
Dependabot doesn't use our semantic versioning aware commit messages.
[Here](https://github.com/codacy/codacy-remark-lint/pull/137) It updated some major remark versions.

**Comment by franciscodua** [comment]
The problem is related to the .remarkignore file. Before the bump, we didn't support it, and 30 issues were on an ignored folder. That's why we're seeing these changes. I added a test for it in #152 and marked the revision as breaking
