### ISSUE TITLE
[CY-2517] GitHub inconsistency

### ISSUE THREAD

**Issue by MuTLY** [codacy/codacy-remark-lint#279]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[X] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
When using MarkDown on `README.MD` files, indenting lists is super confusing. Sometimes it asks for 3 spaces, other times is asks for 4 spaces, why is that? Also, why enforce the use of syntax highlight on code blocks that aren't really "code" but rather just a way of presenting lines of text in a more fashionable way, e.g. lines on a `hosts` file?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by machadoit** [comment]
Hi there @MuTLY,

Can you also share a couple examples? I will add an internal ticket to take a better look at the defaults.

On the scope of this ticket, sometime the defaults don't match the expectations, so please consider customising some patterns on Codacy side, or adding a [.remarkrc](https://github.com/remarkjs/remark-lint#configuring-remark-lint)  to the root of your repository. Would this tackle your issue?

**Comment by machadoit** [comment]
Closing the ticket for now, we will keep the internal ticket to revisit our defaults
