### ISSUE TITLE
[CY-6513] Add remark-gfm

### ISSUE THREAD

**Issue by Glennmen** [codacy/codacy-remark-lint#554]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Currently I am getting a warning:
```
Found [Warning] `[no-undefined-references] Found reference to undefined definition` in README.md:20 (remark-lint-no-undefined-references)
```
This is because I am using a checklist in my markdown, apparently this is Github styled markdown.
Would it be possible to add the remark-gfm plugin so this syntax is also supported.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
https://github.com/remarkjs/remark-gfm

**Comment by stefanvacareanu7** [comment]
Hi Glenn,

I added the plugin. Leave a comment if everything works fine for you.

Enjoy your weekend,
Stefan

**Comment by abbasyadollahi** [comment]
Hey @stefanvacareanu7, how exactly do I use the `remark-gfm` plugin? I'm getting the same `no-undefined-references` errors for my markdown files when I use a checkbox.

> The code line `- [ ] Changes have been documented` is triggering the remark-lint rule `no-undefined-references` because it is referencing a definition that is not defined anywhere in the Markdown file.

Here is the tool as show in the UI:
<img width="184" alt="image" src="https://github.com/codacy/codacy-remark-lint/assets/16931654/d37b2870-b937-4de1-8361-87f1dc83a5eb">

Here is the markdown text (I get the error for both checkbox lines):
```markdown
## 🧪 Tests

- [ ] Changes have been tested
- [ ] Changes have been documented
```

**Comment by abbasyadollahi** [comment]
I believe the issue is that `remark-gfm` wasn't added to the list of exported plugins in [.remarkrc.js](https://github.com/codacy/codacy-remark-lint/blob/master/.remarkrc.js). I could open up a quick PR to add it in the list.
