### ISSUE TITLE
No example YAML file for rules.

### ISSUE THREAD

**Issue by swistak** [codacy/codacy-remark-lint#8]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

Can't find any example how toturn on or off the rules in remark from the level of codacy configuration file.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by IGFCoimbra** [comment]
Hi @swistak,

Right now it is not possible to use Codacy's configuration file to enable or disable patterns on the tools.

If you need any more information on how to use or how to set up the Codacy's configuration file, please reach out to support@codacy.com and we will be able to give you more information there.
